import "./globals.css";
import { Inter } from "next/font/google";
//@ts-ignore
import NavBar from "@/components/navbar/NavBar";
import TopNavBar from "@/components/TopNavBar/TopNavBar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <div className="relative z-30">
            <TopNavBar />
          </div>
          <div className="relative z-20">
            <NavBar />
          </div>
          <div className="pl-0 lg:pl-60 flex-grow overflow-y-auto pt-10 z-60">
            {children}
          </div>
          <div className="pl-0 lg:pl-60 pt-16 pr-4 z-50">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
